### ISSUE TITLE
Popup projects review

### ISSUE THREAD

**Issue by paulinagonzalezc** [paulinagonzalezc/portfolio#11]

**Comment by osamaashraf6** [comment]
## This is my review of this project. 👎 

### High Lights 💯 


- [x] Good commit messages.
- [x] Descriptive READme file  in a professional way.
- [x] No linters errors. 
- [x] Good usage in correcting GitHub flow
- [x] Beautiful UI. 
- [x] Nice design.
- [x] Good code organization.
- [x] Awesome in parsing a Figma design to create a UI.
- [x] Follow our list of best practices for HTML & CSS.
- [x] Follow our list of best practices for JavaScript.



### Optional Suggestions 🔢 

- [x] It would be better if you make a pull request more descriptive  👌😊

**Comment by yayoamigo** [comment]
Highlights:
✔️ No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

      Nice job!

Optional Suggestions: 🔢
-It would be better if you remove the Html that you are not using instead of just commenting out your code

**Comment by paulinagonzalezc** [comment]
Thank you for your comments, I wrote more descriptive pull requests and removed comments on my HTML file as you suggested. 😁
