### ISSUE TITLE
Desktop version Team Review Feedback

### ISSUE THREAD

**Issue by sebalp100** [paulinagonzalezc/portfolio#4]
- I think it would be better to just use one section for media queries.
- Good code so far, easy to read.
- Classes are descriptives.
- Commits are organized.

**Comment by paulinagonzalezc** [comment]
Thank you for your comments, I moved the media queries to one section as you recommended.

**Comment by paulinagonzalezc** [comment]
Thank you for your comments, I moved the media queries to one section as you recommended.
